---
- name: NeoVim のインストール状況を確認
  ansible.builtin.stat:
    path: /opt/nvim-linux-x86_64/bin/nvim
  register: nvim_bin

- name: NeoVim 公式ビルドを /tmp にダウンロード
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim-linux-x86_64.tar.gz
    mode: "0644"
  when: not nvim_bin.stat.exists

- name: NeoVim を /opt に展開
  become: true
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux-x86_64.tar.gz
    dest: /opt
    remote_src: true
  when: not nvim_bin.stat.exists

- name: nvim を /usr/local/bin にシンボリックリンク
  become: true
  ansible.builtin.file:
    src: /opt/nvim-linux-x86_64/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
    force: true
