---
- name: AWS CLI のインストール状況を確認
  ansible.builtin.stat:
    path: /usr/local/bin/aws
  register: aws_bin

- name: unzip がインストールされていることを確認
  become: true
  ansible.builtin.dnf:
    name: unzip
    state: present
  when: not aws_bin.stat.exists

- name: AWS CLI v2 インストーラを /tmp にダウンロード
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: "0644"
  when: not aws_bin.stat.exists

- name: AWS CLI インストーラを展開
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
  when: not aws_bin.stat.exists

- name: AWS CLI v2 をインストール
  become: true
  ansible.builtin.command: /tmp/aws/install
  when: not aws_bin.stat.exists
